[tool.poetry]
name = "matrixanalysis"
version = "0.1.0"
description = "matrix data analysis"
authors = ["sboudcha"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"
pandas = "^2.1.0" #hadi khasni n7ydhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
matplotlib = "3.7.2"
numpy = "^1.24.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"